### ISSUE TITLE
使用Python实现平台自动打卡 | 吾人为学

### ISSUE THREAD

**Issue by mtics** [mtics/mtics.gtihub.io#7]
https://mtics.top/auto-sign-zzu-jksb/#%E4%BB%BB%E5%8A%A1%E5%AE%9A%E6%97%B6 

 该脚本仅用于自动打卡郑州大学健康状况上报平台

**Comment by SZ08** [comment]
博主您好，今天在使用您的脚本时，出现以下错误，请问一下怎么解决，谢谢。
`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='bak_0']/div[19]/div[4]"}
  (Session info: headless chrome=83.0.4103.106)`

**Comment by mtics** [comment]
> 博主您好，今天在使用您的脚本时，出现以下错误，请问一下怎么解决，谢谢。
> `Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='bak_0']/div[19]/div[4]"} (Session info: headless chrome=83.0.4103.106)`

这种错误出现在页面未加载完全的情况下，除了增加等待时间，否则我也不知道怎么解决。如果网页挂了，也是这种错误

**Comment by SZ08** [comment]
博主您好，我想再问一下，实现多用户打卡的话，`private_info.py`这个文件该具体如何编写，能不能请您给一个实例。还有`auto_sign.py`用不用做些更改。我今天尝试的时候，录入了多组用户数据，但只能打卡一个人的。对Python不是很熟悉，希望您能解答一下，谢谢。

**Comment by mtics** [comment]
> 博主您好，我想再问一下，实现多用户打卡的话，`private_info.py`这个文件该具体如何编写，能不能请您给一个实例。还有`auto_sign.py`用不用做些更改。我今天尝试的时候，录入了多组用户数据，但只能打卡一个人的。对Python不是很熟悉，希望您能解答一下，谢谢。

`private_info.py`需要编写的内容和多用户都写在了博客中“私人信息”那一节中了，多用户实际上就是用了列表。
调用时` timing(时, 分, 用户组)`即可

**Comment by olaf-li** [comment]
这个系统Ubuntu能用吗？

**Comment by mtics** [comment]
> 这个系统Ubuntu能用吗？

可以的，只要在系统上配置好环境即可
